// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// label_direction
NumericVector label_direction(NumericVector y, double excursion, int Tinactive);
RcppExport SEXP _tseriespatterns_label_direction(SEXP ySEXP, SEXP excursionSEXP, SEXP TinactiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type excursion(excursionSEXP);
    Rcpp::traits::input_parameter< int >::type Tinactive(TinactiveSEXP);
    rcpp_result_gen = Rcpp::wrap(label_direction(y, excursion, Tinactive));
    return rcpp_result_gen;
END_RCPP
}
// filter_direction
NumericVector filter_direction(NumericVector y, NumericVector vdir, double excursion);
RcppExport SEXP _tseriespatterns_filter_direction(SEXP ySEXP, SEXP vdirSEXP, SEXP excursionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vdir(vdirSEXP);
    Rcpp::traits::input_parameter< double >::type excursion(excursionSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_direction(y, vdir, excursion));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tseriespatterns_label_direction", (DL_FUNC) &_tseriespatterns_label_direction, 3},
    {"_tseriespatterns_filter_direction", (DL_FUNC) &_tseriespatterns_filter_direction, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tseriespatterns(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
