# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

label_direction <- function(y, excursion, Tinactive) {
    .Call(`_tseriespatterns_label_direction`, y, excursion, Tinactive)
}

filter_direction <- function(y, vdir, excursion) {
    .Call(`_tseriespatterns_filter_direction`, y, vdir, excursion)
}

